IPSEC = "ipsec"
PPTP = "pptp"
OPENVPN = "openvpn"
VPN = "VPN"
COMMON_PREFIXES = {
    VPN: "/vpn",
}
SERVICE_TYPE_OPENVPN = "OPENVPN"
SERVICE_TYPE_PPTP = "PPTP"
SERVICE_TYPE_IPSEC = "IPSEC"
VPN_SERVICE_TYPES = [SERVICE_TYPE_IPSEC, SERVICE_TYPE_PPTP, SERVICE_TYPE_OPENVPN]
